# server/problem_templates.py
# 50+ deterministic problem templates for the UX Insight Analyst Environment
# Each template embeds a known UX issue (or red herring) into synthetic analytics data.

from typing import Dict, List, Optional, Any

# ---------------------------------------------------------------------------
# Pages in the simulated "StyleMart" e-commerce platform
# ---------------------------------------------------------------------------

ALL_PAGES = [
    "homepage",
    "category_page",
    "search_results",
    "product_detail_page",
    "cart",
    "checkout",
    "order_confirmation",
    "account_login",
    "wishlist",
    "flash_sale",
]

PAGE_URL_PATTERNS: Dict[str, str] = {
    "homepage": "/",
    "category_page": "/category/{slug}",
    "search_results": "/search?q={query}",
    "product_detail_page": "/products/{id}",
    "cart": "/cart",
    "checkout": "/checkout",
    "order_confirmation": "/order/confirmation/{order_id}",
    "account_login": "/account/login",
    "wishlist": "/wishlist",
    "flash_sale": "/flash-sale",
}

# Default heatmap zones per page
PAGE_HEATMAP_ZONES: Dict[str, List[str]] = {
    "homepage": ["hero_banner", "nav_bar", "category_tiles", "trending_section", "footer"],
    "category_page": ["filter_sidebar", "sort_dropdown", "product_grid", "pagination", "breadcrumbs"],
    "search_results": ["search_bar", "filter_panel", "results_grid", "no_results_msg", "suggested_keywords"],
    "product_detail_page": ["product_image_carousel", "price_section", "size_selector", "add_to_cart_btn", "reviews_section", "related_products"],
    "cart": ["cart_items_list", "quantity_selector", "remove_btn", "promo_code_field", "checkout_cta"],
    "checkout": ["address_form", "payment_options", "order_summary", "place_order_btn", "login_prompt"],
    "order_confirmation": ["order_details", "track_order_btn", "continue_shopping_btn", "cross_sell_section"],
    "account_login": ["email_field", "password_field", "login_btn", "social_login_btns", "forgot_password_link"],
    "wishlist": ["wishlist_items", "move_to_cart_btn", "remove_btn", "share_btn"],
    "flash_sale": ["countdown_timer", "deal_cards", "add_to_cart_btn", "sale_banner"],
}

# ---------------------------------------------------------------------------
# Problem template library — 50+ templates
# ---------------------------------------------------------------------------

PROBLEM_TEMPLATES: List[Dict[str, Any]] = [
    # ==================== RAGE CLICK PROBLEMS ====================
    {
        "problem_id": "RAGE_001",
        "problem_type": "rage_click",
        "affected_page": "product_detail_page",
        "affected_element": "Add to Cart button",
        "severity": "critical",
        "synthetic_signal": {"rage_click_rate": 0.31, "session_count": 4200},
        "description_in_data": "31% of sessions show rage clicks on 'Add to Cart' button in PDP — button appears clickable but does not respond for 3-5 seconds after first click.",
        "expected_keywords": ["add to cart", "rage click", "button", "loading", "feedback", "disabled"],
        "expected_fix_category": "add_loading_state",
        "red_herring": False,
    },
    {
        "problem_id": "RAGE_002",
        "problem_type": "rage_click",
        "affected_page": "checkout",
        "affected_element": "Place Order button",
        "severity": "critical",
        "synthetic_signal": {"rage_click_rate": 0.27, "session_count": 1800},
        "description_in_data": "27% of users rage-click the 'Place Order' button on the checkout page. Button has no loading indicator and no error message on failure.",
        "expected_keywords": ["place order", "rage click", "loading", "feedback", "checkout", "submit"],
        "expected_fix_category": "add_loading_state",
        "red_herring": False,
    },
    {
        "problem_id": "RAGE_003",
        "problem_type": "rage_click",
        "affected_page": "cart",
        "affected_element": "Apply Promo Code button",
        "severity": "high",
        "synthetic_signal": {"rage_click_rate": 0.24, "session_count": 3100},
        "description_in_data": "24% of sessions show rage clicks on the promo code apply button. No visual feedback on submission; users unclear if code was accepted.",
        "expected_keywords": ["promo", "coupon", "rage click", "feedback", "validation", "apply"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },
    {
        "problem_id": "RAGE_004",
        "problem_type": "rage_click",
        "affected_page": "search_results",
        "affected_element": "Sort dropdown",
        "severity": "medium",
        "synthetic_signal": {"rage_click_rate": 0.19, "session_count": 5400},
        "description_in_data": "19% of users rage-click the sort dropdown. The dropdown toggle area is only 24px wide and difficult to target on mobile.",
        "expected_keywords": ["sort", "dropdown", "rage click", "mobile", "touch target", "size"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },
    {
        "problem_id": "RAGE_005",
        "problem_type": "rage_click",
        "affected_page": "account_login",
        "affected_element": "Login button",
        "severity": "high",
        "synthetic_signal": {"rage_click_rate": 0.33, "session_count": 2200},
        "description_in_data": "33% of login attempts show rage clicks on the Login button. The button has no loading state and the form doesn't clear on error.",
        "expected_keywords": ["login", "rage click", "button", "loading", "error", "authentication"],
        "expected_fix_category": "add_loading_state",
        "red_herring": False,
    },

    # ==================== DEAD CLICK PROBLEMS ====================
    {
        "problem_id": "DEAD_001",
        "problem_type": "dead_click",
        "affected_page": "homepage",
        "affected_element": "Flash Sale banner image",
        "severity": "high",
        "synthetic_signal": {"dead_click_rate": 0.28, "session_count": 8100},
        "description_in_data": "28% of users click the Flash Sale banner but it is not a link. Users expect the banner to navigate to the sale page.",
        "expected_keywords": ["banner", "clickable", "link", "dead click", "flash sale", "navigate"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_002",
        "problem_type": "dead_click",
        "affected_page": "product_detail_page",
        "affected_element": "Product image thumbnails",
        "severity": "medium",
        "synthetic_signal": {"dead_click_rate": 0.22, "session_count": 3600},
        "description_in_data": "22% of users click on product image thumbnails expecting to zoom or enlarge, but images are static and non-interactive.",
        "expected_keywords": ["image", "thumbnail", "zoom", "dead click", "enlarge", "interactive"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_003",
        "problem_type": "dead_click",
        "affected_page": "category_page",
        "affected_element": "Product rating stars",
        "severity": "low",
        "synthetic_signal": {"dead_click_rate": 0.15, "session_count": 6800},
        "description_in_data": "15% of users click on the star rating display on category cards expecting to see reviews, but stars are not linked to reviews.",
        "expected_keywords": ["rating", "stars", "reviews", "dead click", "link"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_004",
        "problem_type": "dead_click",
        "affected_page": "cart",
        "affected_element": "Product name in cart item",
        "severity": "medium",
        "synthetic_signal": {"dead_click_rate": 0.18, "session_count": 4100},
        "description_in_data": "18% of users click on the product name in the cart list expecting to navigate back to the PDP, but it is plain text.",
        "expected_keywords": ["product name", "cart", "link", "dead click", "navigate", "PDP"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_005",
        "problem_type": "dead_click",
        "affected_page": "homepage",
        "affected_element": "Trending section title",
        "severity": "low",
        "synthetic_signal": {"dead_click_rate": 0.12, "session_count": 9200},
        "description_in_data": "12% of users click on the 'Trending Now' section header expecting to see a full trending page, but it is not a link.",
        "expected_keywords": ["trending", "header", "dead click", "link", "section"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },

    # ==================== FUNNEL DROPOFF PROBLEMS ====================
    {
        "problem_id": "FUNNEL_001",
        "problem_type": "funnel_dropoff",
        "affected_page": "checkout",
        "affected_element": "Address form — pincode field",
        "severity": "critical",
        "synthetic_signal": {"dropoff_rate": 0.52, "step": "address_entry", "session_count": 2100},
        "description_in_data": "52% of users abandon checkout at the address entry step; 71% of abandoning users stop at the pincode field. Validation errors are unclear.",
        "expected_keywords": ["checkout", "pincode", "address", "form", "abandon", "validation", "drop-off"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },
    {
        "problem_id": "FUNNEL_002",
        "problem_type": "funnel_dropoff",
        "affected_page": "checkout",
        "affected_element": "Payment options section",
        "severity": "high",
        "synthetic_signal": {"dropoff_rate": 0.38, "step": "payment_selection", "session_count": 1500},
        "description_in_data": "38% of users drop off at the payment selection step. UPI option is shown last despite being preferred by 72% of completing users.",
        "expected_keywords": ["payment", "UPI", "drop-off", "order", "checkout", "option"],
        "expected_fix_category": "reposition_element",
        "red_herring": False,
    },
    {
        "problem_id": "FUNNEL_003",
        "problem_type": "funnel_dropoff",
        "affected_page": "cart",
        "affected_element": "Checkout CTA button",
        "severity": "high",
        "synthetic_signal": {"dropoff_rate": 0.44, "step": "cart_to_checkout", "session_count": 5200},
        "description_in_data": "44% of users with items in cart do not proceed to checkout. The checkout CTA is below the fold and requires scrolling past cross-sell suggestions.",
        "expected_keywords": ["checkout", "CTA", "cart", "below fold", "scroll", "visibility"],
        "expected_fix_category": "reposition_element",
        "red_herring": False,
    },
    {
        "problem_id": "FUNNEL_004",
        "problem_type": "funnel_dropoff",
        "affected_page": "account_login",
        "affected_element": "Registration form",
        "severity": "medium",
        "synthetic_signal": {"dropoff_rate": 0.61, "step": "registration", "session_count": 1800},
        "description_in_data": "61% of users who start registration abandon it. The form has 8 required fields including phone verification. Average completion time is 4m 30s.",
        "expected_keywords": ["registration", "form", "abandon", "fields", "simplify", "reduce"],
        "expected_fix_category": "reduce_steps",
        "red_herring": False,
    },

    # ==================== SCROLL DROPOFF PROBLEMS ====================
    {
        "problem_id": "SCROLL_001",
        "problem_type": "scroll_dropoff",
        "affected_page": "product_detail_page",
        "affected_element": "Add to Cart CTA (below fold)",
        "severity": "medium",
        "synthetic_signal": {"scroll_depth_p50": 42, "scroll_depth_p80": 68, "cta_position_percent": 78},
        "description_in_data": "Only 42% of users scroll past the midpoint. The primary 'Add to Cart' CTA is at 78% scroll depth, meaning over half of users never see it.",
        "expected_keywords": ["scroll", "CTA", "above fold", "reposition", "add to cart", "visible"],
        "expected_fix_category": "reposition_element",
        "red_herring": False,
    },
    {
        "problem_id": "SCROLL_002",
        "problem_type": "scroll_dropoff",
        "affected_page": "homepage",
        "affected_element": "Category tiles section",
        "severity": "medium",
        "synthetic_signal": {"scroll_depth_p50": 35, "scroll_depth_p80": 55, "cta_position_percent": 65},
        "description_in_data": "Category navigation tiles are placed at 65% scroll depth. Only 35% of users reach the midpoint, and 55% don't reach the tiles at all.",
        "expected_keywords": ["category", "tiles", "scroll", "above fold", "reposition", "navigation"],
        "expected_fix_category": "reposition_element",
        "red_herring": False,
    },
    {
        "problem_id": "SCROLL_003",
        "problem_type": "scroll_dropoff",
        "affected_page": "flash_sale",
        "affected_element": "Best deals section",
        "severity": "high",
        "synthetic_signal": {"scroll_depth_p50": 28, "scroll_depth_p80": 48, "cta_position_percent": 70},
        "description_in_data": "Only 28% scroll past midpoint on flash sale page. Best deals are at 70% depth. Countdown timer + hero banner occupy the first 40% of the page.",
        "expected_keywords": ["flash sale", "deals", "scroll", "fold", "reposition", "visibility"],
        "expected_fix_category": "reposition_element",
        "red_herring": False,
    },

    # ==================== MOBILE LAYOUT PROBLEMS ====================
    {
        "problem_id": "MOBILE_001",
        "problem_type": "mobile_layout_break",
        "affected_page": "category_page",
        "affected_element": "Filter sidebar",
        "severity": "high",
        "synthetic_signal": {"mobile_bounce_rate": 0.71, "desktop_bounce_rate": 0.28, "mobile_sessions_pct": 0.68},
        "description_in_data": "Mobile bounce rate (71%) is 2.5x desktop (28%). 68% of traffic is mobile. Filter sidebar overlaps product grid on screens < 375px.",
        "expected_keywords": ["mobile", "filter", "sidebar", "responsive", "overlap", "layout", "bounce"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },
    {
        "problem_id": "MOBILE_002",
        "problem_type": "mobile_layout_break",
        "affected_page": "checkout",
        "affected_element": "UPI payment button",
        "severity": "critical",
        "synthetic_signal": {"mobile_bounce_rate": 0.58, "desktop_bounce_rate": 0.22, "mobile_sessions_pct": 0.72},
        "description_in_data": "Mobile checkout bounce rate is 58% vs desktop 22%. UPI button is not rendering on iOS Safari due to CSS overflow:hidden on mobile viewport.",
        "expected_keywords": ["mobile", "UPI", "payment", "iOS", "button", "render", "layout"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },
    {
        "problem_id": "MOBILE_003",
        "problem_type": "mobile_layout_break",
        "affected_page": "product_detail_page",
        "affected_element": "Size selector dropdown",
        "severity": "high",
        "synthetic_signal": {"mobile_bounce_rate": 0.49, "desktop_bounce_rate": 0.24, "mobile_sessions_pct": 0.65},
        "description_in_data": "Mobile bounce rate on PDP is 49% vs desktop 24%. Size selector dropdown is cut off on mobile, showing only 2 of 6 sizes. Users cannot scroll within the dropdown.",
        "expected_keywords": ["mobile", "size", "selector", "dropdown", "layout", "scroll", "truncated"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },
    {
        "problem_id": "MOBILE_004",
        "problem_type": "mobile_layout_break",
        "affected_page": "search_results",
        "affected_element": "Search result cards",
        "severity": "medium",
        "synthetic_signal": {"mobile_bounce_rate": 0.55, "desktop_bounce_rate": 0.31, "mobile_sessions_pct": 0.70},
        "description_in_data": "Mobile bounce rate (55%) is 1.8x desktop (31%). Product card text overflows and price is truncated on screens < 360px.",
        "expected_keywords": ["mobile", "search", "card", "text", "overflow", "truncated", "price"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },

    # ==================== QUICKBACK PROBLEMS ====================
    {
        "problem_id": "QUICKBACK_001",
        "problem_type": "quickback",
        "affected_page": "category_page",
        "affected_element": "Category navigation labels",
        "severity": "high",
        "synthetic_signal": {"quickback_rate": 0.38, "session_count": 5800},
        "description_in_data": "38% quickback rate from category page to homepage. Users navigate to a category, see unexpected products, and immediately return. Category labels may be misleading.",
        "expected_keywords": ["quickback", "category", "navigation", "label", "misleading", "mismatch"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },
    {
        "problem_id": "QUICKBACK_002",
        "problem_type": "quickback",
        "affected_page": "product_detail_page",
        "affected_element": "Product listing image",
        "severity": "medium",
        "synthetic_signal": {"quickback_rate": 0.29, "session_count": 4500},
        "description_in_data": "29% quickback from PDP to category/search. Users click a product, see it doesn't match the thumbnail/listing image, and immediately go back.",
        "expected_keywords": ["quickback", "product", "image", "thumbnail", "mismatch", "misleading"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },
    {
        "problem_id": "QUICKBACK_003",
        "problem_type": "quickback",
        "affected_page": "flash_sale",
        "affected_element": "Flash sale page",
        "severity": "medium",
        "synthetic_signal": {"quickback_rate": 0.42, "session_count": 3200},
        "description_in_data": "42% quickback rate from flash sale page. Users arrive but the sale has expired; countdown timer shows 00:00 but page is still accessible with full prices.",
        "expected_keywords": ["quickback", "flash sale", "expired", "timer", "redirect", "stale"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },

    # ==================== FORM ABANDONMENT PROBLEMS ====================
    {
        "problem_id": "FORM_001",
        "problem_type": "form_abandonment",
        "affected_page": "checkout",
        "affected_element": "Shipping address form",
        "severity": "high",
        "synthetic_signal": {"abandonment_rate": 0.47, "session_count": 2800},
        "description_in_data": "47% of users abandon the shipping address form. The form has 12 fields and no auto-fill support. Avg time spent before abandon: 2m 45s.",
        "expected_keywords": ["form", "address", "abandon", "fields", "auto-fill", "simplify"],
        "expected_fix_category": "reduce_steps",
        "red_herring": False,
    },
    {
        "problem_id": "FORM_002",
        "problem_type": "form_abandonment",
        "affected_page": "account_login",
        "affected_element": "Password field",
        "severity": "medium",
        "synthetic_signal": {"abandonment_rate": 0.35, "session_count": 3400},
        "description_in_data": "35% of users abandon at the password field during login. Error message 'Invalid credentials' is generic; no password visibility toggle exists.",
        "expected_keywords": ["password", "login", "abandon", "error", "visibility", "toggle"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },

    # ==================== CTA INVISIBLE PROBLEMS ====================
    {
        "problem_id": "CTA_001",
        "problem_type": "cta_invisible",
        "affected_page": "product_detail_page",
        "affected_element": "Buy Now button",
        "severity": "high",
        "synthetic_signal": {"click_rate": 0.03, "session_count": 7200, "contrast_ratio": 1.8},
        "description_in_data": "Buy Now button has only 3% click rate with 7,200 sessions. Button color (#E8E8E8 on #F5F5F5) has contrast ratio of 1.8:1, well below WCAG minimum of 4.5:1.",
        "expected_keywords": ["button", "contrast", "visibility", "color", "CTA", "WCAG", "click rate"],
        "expected_fix_category": "increase_contrast",
        "red_herring": False,
    },
    {
        "problem_id": "CTA_002",
        "problem_type": "cta_invisible",
        "affected_page": "cart",
        "affected_element": "Proceed to Checkout button",
        "severity": "high",
        "synthetic_signal": {"click_rate": 0.05, "session_count": 5100, "contrast_ratio": 2.1},
        "description_in_data": "Proceed to Checkout button has 5% click rate. It's styled as a ghost button (outline only) in light gray, nearly invisible against white background.",
        "expected_keywords": ["checkout", "button", "ghost", "contrast", "visibility", "CTA", "invisible"],
        "expected_fix_category": "increase_contrast",
        "red_herring": False,
    },

    # ==================== SEARCH NO RESULTS PROBLEMS ====================
    {
        "problem_id": "SEARCH_001",
        "problem_type": "search_no_results",
        "affected_page": "search_results",
        "affected_element": "Search results page — no results state",
        "severity": "medium",
        "synthetic_signal": {"no_results_rate": 0.23, "session_count": 11000, "exit_after_no_results": 0.78},
        "description_in_data": "23% of search queries return 0 results. 78% of users who see 'No results' exit the app. No suggested alternatives or spelling corrections are shown.",
        "expected_keywords": ["search", "no results", "suggestions", "spelling", "alternative", "exit"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },
    {
        "problem_id": "SEARCH_002",
        "problem_type": "search_no_results",
        "affected_page": "search_results",
        "affected_element": "Search autocomplete",
        "severity": "medium",
        "synthetic_signal": {"no_results_rate": 0.18, "session_count": 8500, "typo_rate": 0.42},
        "description_in_data": "18% no-results rate. 42% of no-result queries have typos that autocomplete did not catch. Autocomplete only matches exact prefixes, not fuzzy matches.",
        "expected_keywords": ["search", "autocomplete", "typo", "fuzzy", "matching", "spelling"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },

    # ==================== HIGH BOUNCE (MISC) PROBLEMS ====================
    {
        "problem_id": "BOUNCE_001",
        "problem_type": "high_bounce",
        "affected_page": "homepage",
        "affected_element": "Hero banner — auto-carousel",
        "severity": "medium",
        "synthetic_signal": {"bounce_rate": 0.58, "avg_time_on_page": 4.2},
        "description_in_data": "58% bounce rate on homepage. Average time-on-page is only 4.2 seconds. Hero auto-carousel rotates every 2 seconds — users may be disoriented.",
        "expected_keywords": ["bounce", "homepage", "carousel", "auto-rotate", "speed", "distracting"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },
    {
        "problem_id": "BOUNCE_002",
        "problem_type": "high_bounce",
        "affected_page": "flash_sale",
        "affected_element": "Flash sale page — slow load",
        "severity": "high",
        "synthetic_signal": {"bounce_rate": 0.67, "avg_load_time": 8.3},
        "description_in_data": "67% bounce rate on flash sale page. Average page load time is 8.3 seconds. Heavy animated countdown + unoptimized deal card images.",
        "expected_keywords": ["bounce", "flash sale", "load time", "slow", "performance", "optimize"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },

    # ==================== RED HERRING PROBLEMS (Hard task only) ====================
    {
        "problem_id": "REDHERRING_001",
        "problem_type": "high_bounce",
        "affected_page": "order_confirmation",
        "affected_element": "Order confirmation page",
        "severity": "low",
        "synthetic_signal": {"bounce_rate": 0.89},
        "description_in_data": "89% of users leave the site from the order confirmation page.",
        "expected_keywords": [],
        "expected_fix_category": None,
        "red_herring": True,
        "red_herring_explanation": "High exit rate on order confirmation is expected — the purchase task is complete. Users naturally leave after seeing their order confirmation.",
    },
    {
        "problem_id": "REDHERRING_002",
        "problem_type": "high_bounce",
        "affected_page": "order_confirmation",
        "affected_element": "Order confirmation — time on page",
        "severity": "low",
        "synthetic_signal": {"bounce_rate": 0.92, "avg_time_on_page": 12.5},
        "description_in_data": "92% exit rate with 12.5 second average time on page. Users view confirmation details and leave.",
        "expected_keywords": [],
        "expected_fix_category": None,
        "red_herring": True,
        "red_herring_explanation": "Users spending 12.5 seconds reading confirmation details and then leaving is perfectly normal post-purchase behavior.",
    },
    {
        "problem_id": "REDHERRING_003",
        "problem_type": "scroll_dropoff",
        "affected_page": "product_detail_page",
        "affected_element": "Product reviews section — high engagement",
        "severity": "low",
        "synthetic_signal": {"scroll_depth_p50": 82, "scroll_depth_p80": 95, "avg_time_on_page": 185},
        "description_in_data": "Users scroll deeply (p50=82%, p80=95%) and spend 3+ minutes on PDP. High scroll engagement.",
        "expected_keywords": [],
        "expected_fix_category": None,
        "red_herring": True,
        "red_herring_explanation": "Deep scrolling and high time-on-page on a PDP indicates strong content engagement, not a problem. Users are reading reviews thoroughly.",
    },
    {
        "problem_id": "REDHERRING_004",
        "problem_type": "high_bounce",
        "affected_page": "account_login",
        "affected_element": "Login success redirect",
        "severity": "low",
        "synthetic_signal": {"bounce_rate": 0.76, "avg_time_on_page": 8.0},
        "description_in_data": "76% of sessions on the login page 'bounce' — but users are being redirected to their destination page after successful login.",
        "expected_keywords": [],
        "expected_fix_category": None,
        "red_herring": True,
        "red_herring_explanation": "Login page 'bounces' are actually successful redirects. Users log in and get redirected to their target page, which analytics records as a bounce.",
    },
    {
        "problem_id": "REDHERRING_005",
        "problem_type": "quickback",
        "affected_page": "wishlist",
        "affected_element": "Wishlist page — low time",
        "severity": "low",
        "synthetic_signal": {"quickback_rate": 0.15, "avg_time_on_page": 6.0},
        "description_in_data": "15% quick-return rate from wishlist. Average time on page is 6 seconds.",
        "expected_keywords": [],
        "expected_fix_category": None,
        "red_herring": True,
        "red_herring_explanation": "15% quickback is within normal range. Users may briefly check wishlist and navigate to a specific product — this is efficient navigation, not frustration.",
    },

    # ==================== ADDITIONAL REAL PROBLEMS (for variety) ====================
    {
        "problem_id": "RAGE_006",
        "problem_type": "rage_click",
        "affected_page": "wishlist",
        "affected_element": "Move to Cart button",
        "severity": "high",
        "synthetic_signal": {"rage_click_rate": 0.26, "session_count": 1900},
        "description_in_data": "26% rage click rate on 'Move to Cart' button in wishlist. Button triggers a confirmation modal that loads slowly (2-4s delay).",
        "expected_keywords": ["wishlist", "move to cart", "rage click", "modal", "loading", "delay"],
        "expected_fix_category": "add_loading_state",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_006",
        "problem_type": "dead_click",
        "affected_page": "product_detail_page",
        "affected_element": "Delivery estimate text",
        "severity": "low",
        "synthetic_signal": {"dead_click_rate": 0.14, "session_count": 5100},
        "description_in_data": "14% of users click on the delivery estimate text ('Delivers in 3-5 days') expecting more shipping details, but it is not interactive.",
        "expected_keywords": ["delivery", "shipping", "dead click", "details", "expand", "link"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },
    {
        "problem_id": "FUNNEL_005",
        "problem_type": "funnel_dropoff",
        "affected_page": "checkout",
        "affected_element": "Order review step",
        "severity": "medium",
        "synthetic_signal": {"dropoff_rate": 0.29, "step": "order_review", "session_count": 1200},
        "description_in_data": "29% drop-off at order review step. Users see shipping fee for first time here. Pricing surprise causes abandonment.",
        "expected_keywords": ["order review", "shipping", "fee", "surprise", "pricing", "transparent"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },
    {
        "problem_id": "MOBILE_005",
        "problem_type": "mobile_layout_break",
        "affected_page": "homepage",
        "affected_element": "Navigation hamburger menu",
        "severity": "medium",
        "synthetic_signal": {"mobile_bounce_rate": 0.52, "desktop_bounce_rate": 0.33, "mobile_sessions_pct": 0.67},
        "description_in_data": "Mobile bounce 52% vs desktop 33%. Hamburger menu icon is only 16x16px on mobile, below the recommended 44x44px touch target.",
        "expected_keywords": ["mobile", "hamburger", "menu", "touch target", "size", "navigation"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },
    {
        "problem_id": "QUICKBACK_004",
        "problem_type": "quickback",
        "affected_page": "search_results",
        "affected_element": "Search results relevance",
        "severity": "high",
        "synthetic_signal": {"quickback_rate": 0.35, "session_count": 7200},
        "description_in_data": "35% quickback rate from search results. Users search for specific items but results show loosely related products. Search algorithm may be too broad.",
        "expected_keywords": ["search", "quickback", "relevance", "results", "algorithm", "mismatch"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },
    {
        "problem_id": "FORM_003",
        "problem_type": "form_abandonment",
        "affected_page": "checkout",
        "affected_element": "Phone number field",
        "severity": "medium",
        "synthetic_signal": {"abandonment_rate": 0.31, "session_count": 2200},
        "description_in_data": "31% abandonment at phone number field. Field requires country code in specific format (+91XXXXXXXXXX) but no format hint is shown.",
        "expected_keywords": ["phone", "number", "format", "hint", "validation", "country code"],
        "expected_fix_category": "improve_copy",
        "red_herring": False,
    },
    {
        "problem_id": "CTA_003",
        "problem_type": "cta_invisible",
        "affected_page": "homepage",
        "affected_element": "Shop Now button on hero banner",
        "severity": "medium",
        "synthetic_signal": {"click_rate": 0.04, "session_count": 10200, "contrast_ratio": 2.0},
        "description_in_data": "Shop Now button on hero banner has 4% click rate. White text on light gradient background. Contrast ratio 2.0:1.",
        "expected_keywords": ["shop now", "button", "contrast", "hero", "banner", "visibility", "text"],
        "expected_fix_category": "increase_contrast",
        "red_herring": False,
    },
    {
        "problem_id": "BOUNCE_003",
        "problem_type": "high_bounce",
        "affected_page": "category_page",
        "affected_element": "Category page — empty state",
        "severity": "high",
        "synthetic_signal": {"bounce_rate": 0.72, "empty_category_pct": 0.15},
        "description_in_data": "72% bounce rate. 15% of category page loads show an empty product grid due to inventory sync lag. No 'check back soon' message or alternatives.",
        "expected_keywords": ["bounce", "category", "empty", "inventory", "fallback", "message"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },
    {
        "problem_id": "RAGE_007",
        "problem_type": "rage_click",
        "affected_page": "flash_sale",
        "affected_element": "Countdown timer",
        "severity": "medium",
        "synthetic_signal": {"rage_click_rate": 0.17, "session_count": 2800},
        "description_in_data": "17% rage click rate on countdown timer. Users click on the timer expecting it to reveal deal details, but it is not interactive.",
        "expected_keywords": ["countdown", "timer", "rage click", "interactive", "flash sale"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },
    {
        "problem_id": "DEAD_007",
        "problem_type": "dead_click",
        "affected_page": "checkout",
        "affected_element": "Order summary — item image",
        "severity": "low",
        "synthetic_signal": {"dead_click_rate": 0.11, "session_count": 1600},
        "description_in_data": "11% of users click on item thumbnail images in order summary during checkout, expecting to return to PDP.",
        "expected_keywords": ["order summary", "image", "checkout", "dead click", "link", "PDP"],
        "expected_fix_category": "fix_broken_link",
        "red_herring": False,
    },
    {
        "problem_id": "SCROLL_004",
        "problem_type": "scroll_dropoff",
        "affected_page": "category_page",
        "affected_element": "Pagination controls",
        "severity": "medium",
        "synthetic_signal": {"scroll_depth_p50": 48, "scroll_depth_p80": 72, "cta_position_percent": 95},
        "description_in_data": "Pagination is at 95% scroll depth. Only 48% reach midpoint. Most users never see page 2+ of results. Infinite scroll would improve discovery.",
        "expected_keywords": ["pagination", "scroll", "infinite scroll", "discovery", "bottom", "depth"],
        "expected_fix_category": "redesign_element",
        "red_herring": False,
    },
    {
        "problem_id": "MOBILE_006",
        "problem_type": "mobile_layout_break",
        "affected_page": "cart",
        "affected_element": "Quantity selector buttons",
        "severity": "medium",
        "synthetic_signal": {"mobile_bounce_rate": 0.44, "desktop_bounce_rate": 0.25, "mobile_sessions_pct": 0.66},
        "description_in_data": "Mobile cart bounce 44% vs desktop 25%. Plus/minus quantity buttons are 18x18px on mobile — too small for touch. Misclicks trigger remove-item confirmation.",
        "expected_keywords": ["mobile", "quantity", "button", "touch target", "small", "cart"],
        "expected_fix_category": "fix_mobile_layout",
        "red_herring": False,
    },
    {
        "problem_id": "QUICKBACK_005",
        "problem_type": "quickback",
        "affected_page": "product_detail_page",
        "affected_element": "Out of stock notice",
        "severity": "high",
        "synthetic_signal": {"quickback_rate": 0.51, "session_count": 3100},
        "description_in_data": "51% quickback rate. Users land on PDP only to find item is out of stock. No indication in the category page listing that the item is unavailable.",
        "expected_keywords": ["quickback", "out of stock", "stock", "indicator", "category", "availability"],
        "expected_fix_category": "add_feedback",
        "red_herring": False,
    },
]

# Index: problems grouped by page
PROBLEMS_BY_PAGE: Dict[str, List[Dict[str, Any]]] = {}
for _t in PROBLEM_TEMPLATES:
    pg = _t["affected_page"]
    PROBLEMS_BY_PAGE.setdefault(pg, []).append(_t)

# Index: problems by type
PROBLEMS_BY_TYPE: Dict[str, List[Dict[str, Any]]] = {}
for _t in PROBLEM_TEMPLATES:
    pt = _t["problem_type"]
    PROBLEMS_BY_TYPE.setdefault(pt, []).append(_t)

# Related category pairs (for partial credit on close-but-not-exact matches)
RELATED_CATEGORIES = {
    ("rage_click", "dead_click"),
    ("dead_click", "rage_click"),
    ("funnel_dropoff", "form_abandonment"),
    ("form_abandonment", "funnel_dropoff"),
    ("scroll_dropoff", "cta_invisible"),
    ("cta_invisible", "scroll_dropoff"),
    ("quickback", "high_bounce"),
    ("high_bounce", "quickback"),
    ("mobile_layout_break", "cta_invisible"),
}

# Compatible fix category pairs
COMPATIBLE_FIXES = {
    ("add_loading_state", "add_feedback"),
    ("add_feedback", "add_loading_state"),
    ("fix_broken_link", "redesign_element"),
    ("redesign_element", "fix_broken_link"),
    ("improve_copy", "add_feedback"),
    ("add_feedback", "improve_copy"),
    ("reposition_element", "redesign_element"),
    ("redesign_element", "reposition_element"),
    ("reduce_steps", "redesign_element"),
    ("fix_mobile_layout", "redesign_element"),
    ("increase_contrast", "redesign_element"),
}
